### ISSUE TITLE
Bug: applyMiddlewareToDeclaredResolvers works only for first middleware

### ISSUE THREAD

**Issue by rostislavv** [prisma-labs/graphql-middleware#241]
On top of this issue https://github.com/maticzav/graphql-shield/issues/416 we faced noticeable performance degradation when `graphql-shield` applied. After few stages of investigation it turned out that there is a small bug in `graphql-middleware` itself, where for `applyMiddlewareToDeclaredResolvers` it will apply to declared resolver only for first middleware in sequence [here](https://github.com/prisma-labs/graphql-middleware/blob/master/src/applicator.ts#L93), and all fields will be affected for next middlewares, due to presence of field, and passing of [this](https://github.com/prisma-labs/graphql-middleware/blob/master/src/applicator.ts#L61) condition

**Comment by rostislavv** [comment]
i've also prepared pr for this https://github.com/prisma-labs/graphql-middleware/pull/242

**Comment by maticzav** [comment]
@rostislavv thanks. Your PR is invaluable to `graphql-shield` and `graphql-middleware`! 🙂

**Comment by rostislavv** [comment]
np, thank you for your work 👍
