### ISSUE TITLE
Apply middleware by data sources

### ISSUE THREAD

**Issue by serraventura** [prisma-labs/graphql-middleware#252]
Is there a way to apply the middleware just for some data sources?

I have multiple data sources and not all of them need to use my middlewares for its resolvers.

Does it make sense at all ?

Thanks

**Comment by maticzav** [comment]
@serraventura could you be a bit more specific about what you mean with data sources?

**Comment by serraventura** [comment]
I will be back with code examples. Please, don't close it.
Thanks

**Comment by serraventura** [comment]
Sorry, It's unrelated to your package.
